version: "3.7"
services:
  app:
    build:
      args:
        user: drcnba
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image:  drconsulta-nba-php
    container_name: drconsulta-nba-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - drconsultanba

  nginx:
    image: nginx:alpine
    container_name: drconsulta-nba-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - drconsultanba

networks:
  drconsultanba:
    driver: bridge